# Generated by Django 5.0.3 on 2026-03-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('NO_DISPONIBLE', 'NO_DISPONIBLE')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='AlquilerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='infrastructure.equipomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='infrastructure.usuariomodel')),
            ],
            options={
                'db_table': 'alquiler',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('TARJETA', 'TARJETA'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('EFECTIVO', 'EFECTIVO')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('FALLIDO', 'FALLIDO')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField()),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='infrastructure.alquilermodel')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='PenalizacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='infrastructure.alquilermodel')),
            ],
            options={
                'db_table': 'penalizacion',
            },
        ),
    ]
