# Generated by Django 5.0.3 on 2026-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomodel',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('NO_DISPONIBLE', 'NO_DISPONIBLE'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
